# Generated by Django 3.1.1 on 2020-10-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20201005_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='email',
            field=models.CharField(default='', max_length=60),
        ),
    ]
